### ISSUE TITLE
yobit-exchange-api Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by hatemgh123** [ballantyne/yobit-exchange-api#1]
hello i installed yobit-exchange-api
and when i runing server 
i got this error 
boom!

```

> Failed to load https://yobit.net/api/2/ltc_btc/ticker: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> undefined

```

help plz

**Comment by ballantyne** [comment]
I have only ever used the library from the server side.  Are you using it
with browserify or webpack?

How do you store the api token?  Maybe it would be better to use that code
on the server?

I think if you need to add cors you just add that header to the request.  I
actually don’t have any code using this library right now.  Can you try to
find a solution?

**Comment by ballantyne** [comment]
https://github.com/ballantyne/yobit-exchange-api/blob/master/lib/http.js#L25-L36
That is where the headers get added.  You could add the header you need to that function.  I think that I initially was going to make it so that the headers function uses the _.extend function to merge the params, but that function doesn't seem to be doing anything except adding a user-agent.  Seems like it shouldn't be too difficult to add a header that allows any origin.  I am unfamiliar with request's no-cors mode.

**Comment by ballantyne** [comment]
https://github.com/ballantyne/yobit-exchange-api/blob/master/lib/authenticated.js#L15-L17
Looks like there is something happening in the authenticated version of the class.  Not sure if adding strange headers will bother the signature.  You might have to make the change here.  Experiment and see if you can find a solution that you are happy with.  The signature returns an object, so I get you could try to add that to the object after signing?
https://github.com/ballantyne/yobit-exchange-api/blob/master/lib/signature.js
